message(paste(format(Sys.time(), "%A, %d %B %Y pukul %X"), Sys.timezone(), sep = " "))
message("Starting the machine...")
suppressPackageStartupMessages(source("requirement.R"))
get_vacancy("glints")
get_vacancy("jobstreet")
