name: jobcrawler
on:
  workflow_dispatch:

jobs:
  job-crawler:
    runs-on: ubuntu-latest
    env:
      R_TELEGRAM_BOT_IDNRBOT: ${{ secrets.R_TELEGRAM_BOT_IDNRBOT }}
      ADMIN_ID: ${{ secrets.ADMIN_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependency
        run: sudo apt install libcurl4-openssl-dev
      - name: Install R packages
        run: R -e 'install.packages(c("dplyr", "httr", "janitor", "jsonlite", "rvest", "stringr", "telegram.bot", "tidyr"), dependencies = TRUE)'
      - name: Run crawler and forwarder script
        run: Rscript postman.R
      - name: Commit results to main branch
        run: |
          git config --global user.email "akherlan@users.noreply.github.com"
          git config --global user.name "Andi"
          git commit -am "New update" || echo "No changes to commit"
          git push origin || echo "No changes to commit"

